### ISSUE TITLE
QC labels: must be able to read multiple potential label name for a given label value

### ISSUE THREAD

**Issue by laurentletg** [llgneuroresearch/avnirpy#10]
## Expected Behavior

In some older projects or when there are manual edits it is possible that there are multiple ways the same label was entered: 
e.g. 
`ICH, HIP, hemorrhage` for value 1. 

## Actual Behavior
The script currently looks for a single label name to match a given value
e.g. `ICH : 1 `
This requires manual correction of all segments that failed this qc step. 

## Potential solution
Change the configuration file to include a read and write subsection. 
```yaml
labels: 
  - name: "ICH"
    value: 1
    aliases: ["ICH", "HIP", "hemorrhage"]
```
and adapt the script accordingly
